#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwuSNRSGNl7xKj+tdUQUmhpVu9VRPnBbs/rUxpJCo+lGTRB4MGS1me0dpybkfpHPs7inJhdj0X80Ja/APEBf4WByVH59Wr37zrrKbYO7DfbtVrcXjixIzPe2a7ADCgSMDMELhbCCwHMcl+8Uq97ky0Vq4pP3zeOVDwJ5JQpPqj+nPkJPOEsxZXpMOI3Swekgo++oV7Eitjqfayfvv3vV58pDt3mxrdfVXBrZAlNzzoSeGXSevHOwzw/OU65R3hVO8HbY8OgJ4CRRSsUX6tZV7u4aX5JOXTahEwlcLJYof7na+Z0F9sCYf5y9gO98QguEmFc+b4ewFrDaHW47Qi+P0h aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - curl
  - wget